version: "3.7"


services:
    api-service:
        build: ./app
        volumes:
            - ./app:/usr/src/app
        ports:
            - 5001:80

    website:
        image: php:apache
        volumes:
            - ./website:/var/www/html
        ports:
            - 5000:80
        depends_on:
            - api-service